### ISSUE TITLE
Certbot on CentOS seems to have broken down

### ISSUE THREAD

**Issue by andreby** [ICOS-Carbon-Portal/infrastructure#2]
This happens when I try to deploy cpauth on a freshly created CentOS VM.  I seems as though something has changed in the packaging of the certbot packag, and not all of its dependencies are installed.

```
TASK [icos.cpauth : Install SSL certificate] ***********************************
fatal: [centos]: FAILED! => {
    "changed": true, 
    "cmd": [
        "certbot", 
        "--authenticator", 
        "webroot", 
        "--installer", 
        "nginx", 
        "--non-interactive", 
        "--webroot-path", 
        "/usr/share/nginx/html/", 
        "--domain", 
        "cpauth.icos-cp.eu", 
        "--domain", 
        "auth.fieldsites.se", 
        "--email", 
        "carbon.admin@nateko.lu.se", 
        "--agree-tos"
    ], 
    "delta": "0:00:00.625625", 
    "end": "2018-04-05 02:37:49.216473", 
    "rc": 1, 
    "start": "2018-04-05 02:37:48.590848"
}

STDERR:

Traceback (most recent call last):
  File "/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.22.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 17, in <module>
    from certbot import account
  File "/usr/lib/python2.7/site-packages/certbot/account.py", line 17, in <module>
    from acme import messages
  File "/usr/lib/python2.7/site-packages/acme/messages.py", line 7, in <module>
    from acme import challenges
  File "/usr/lib/python2.7/site-packages/acme/challenges.py", line 11, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'
```

**Comment by jonathanthiry** [comment]
Certificates are not requested anymore on test VMs and installation works in production.
